### ISSUE TITLE
Support "minipay easy connection"

### ISSUE THREAD

**Issue by silasbw** [celo-org/staked-celo-web-app#228]
### Component

Other (please describe)

### Describe the feature you would like

Support the [build-on-minipay](https://docs.celo.org/developer/build-on-minipay/overview#integration-with-popular-web3-libraries) pattern.

Users often exit a dapp after they've opened it, but before they connect their wallet.  One _potential_ reason is that the wallet connection UX is confusing. For example, it might require the user to know implementation details about their wallet (_e.g._, it uses WalletConnect) or it might simply be an unexpected next step (_e.g._, "what does it mean to connect my wallet if I opened this app in my wallet?").

[build-on-minipay](https://docs.celo.org/developer/build-on-minipay/overview#integration-with-popular-web3-libraries) has one approach for eliminating wallet connection confusion when an injected provider is available.

**Comment by arthurgousset** [comment]
Thanks for sharing this here @silasbw! Really appreciate it :) 

Since the front-end for [app.stcelo.xyz](https://app.stcelo.xyz/) is open-source in this repository ([celo-org/staked-celo-web-app](https://github.com/celo-org/staked-celo-web-app)), we would happily welcome a draft PR from the Valora team and provide a code review.

Would one of the Valora engineers be open to working on a draft PR?
